[package]
name = "mailboxd-blob"
version = "0.1.0"
edition = "2021"
description = "Embedded KV storage engine for email"

[dependencies]
crc32fast = "1.4"
zstd = "0.14"
lz4_flex = "0.14.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = { package = "bincode_reloaded", version = "3.1.10", default-features = false, features = ["serde", "alloc"] }
tracing = "0.1"
thiserror = "2"
redb = "4.2.0"
fs2 = "0.4.3"

[dev-dependencies]
tempfile = "=3.27.0"
rand = "=0.10.2"
criterion = { version = "=0.8.2", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
